language: node_js
node_js:
- 12

services:
- docker

matrix:
  include:
  - os: linux
    arch: amd64
    env: ARCH=amd64
  - os: linux
    arch: arm64
    env: ARCH=arm32v7

# Nothing to do
install:

script:
- npx dockerfile-template -d ARCH=$ARCH Dockerfile.template | docker build -f - -t docker.pkg.github.com/leichtbau/dockerize/$ARCH:latest .

deploy:
  - provider: script
    on:
      tags: true
    script: bash scripts/docker_push_ci
env:
  global:
    secure: d3uhRJcC/bybFjuet9bxROgs8s2nrdq0F8yn72njzZ2jHVlhrVsXtxU/7Qcg7hLYde9MhDN7hbvto3FP6DMwu7/6V8sHYKOg1CTuEB7egeH5tMatAzn1j024T0klgDLyVZQ3nARtGWG6RaMLe+DONFADdIg6OnsFscE1OhDcb8ncj7Gg+e5DQLMB22UAAY35Jc9YBPkZeiYlVWyOAZPZxTDjn9RCmlZVV8rrQh221t1pwYs5RBrsYRD4zO2AuBnRJfLASYxDQbW6AN2tNicAjMds2Ho52mbyCMs5IrGN3Lz9bMkUGljwbHQ2LP5KVx7V8mZpvdqgYHSPln8K/iQHRqhqQq3IoyMfhe4dibaAxpoCA6KH8o6gziM48HJz9hl13ingoVoLPRTNpUUyzN1fEqSuuKCv3ofOlLe9pIAkJpTAutj1upNHoFSBeACb13BZYpnryDifuPSCSQWm3vMeSONg0RkxzrfkpNyiocncTYINirQVO+75GzzWKbaqs9qQH5I3uTwmw5WoKZLSL0tnHy1nCTFW4xKnQPDjGVf+Ui4EW/j30N56a5ps8uneMh0Yvex4NiL96LQb9yuS330gYuABSEVyPMZ+4wV7wFZT2q9HViSMa0mOS1ZlY08DJxXbiBX96XtWo5je73nX/K9hkdWL8hjL8wmCb/zHlgZHltQ=
